export const SYSTEM_META = {
  osName: "ChiragOS",
  osVersion: "2.6.0",
  edition: "Multi-Screen Developer Workstation",
  buildDate: "2026.09",
  owner: "Chirag Chaudhary",
  role: "Software Engineer at TCS",
  title: "Chirag Chaudhary — Software Engineer | 3D Interactive Portfolio (Flutter, Dart, NestJS)",
  description: "Official 3D interactive developer portfolio of Chirag Chaudhary, Software Engineer at Tata Consultancy Services (TCS) and creator of flutter_blueprint on Pub.dev. Specializing in enterprise Flutter, Dart, NestJS, TypeScript, and Next.js.",
  url: "https://chirag640.github.io/desk-look-portfolio",
  siteName: "Chirag Chaudhary — 3D Portfolio",
  github: "https://github.com/chirag640",
  linkedin: "https://www.linkedin.com/in/chiragchaudhary1910/",
  pubDev: "https://pub.dev/packages/flutter_blueprint",
  email: "chiragchaudhary1910@gmail.com",
  keywords: [
    "Chirag Chaudhary",
    "Chirag",
    "Software Engineer",
    "Tata Consultancy Services",
    "TCS",
    "TCS Digital",
    "flutter_blueprint",
    "Flutter Developer",
    "Dart Developer",
    "NestJS",
    "Next.js 16",
    "TypeScript",
    "Node.js",
    "Pub.dev package author",
    "Clean Architecture Flutter",
    "BLoC",
    "Riverpod",
    "PostgreSQL",
    "Docker",
    "3D Portfolio",
    "Three.js Portfolio",
    "React Three Fiber"
  ]
};

